In [1]:
import numpy as np

# Creating Numpy Array

1. np.arrays()

2. np.ones()

3. np.zeros()

4. np.arange()

5. np.linspace()

6. copy()

7. np.identity()

###  Using np.array()

In [2]:
arr1=np.array([1,2,3,4,5])

In [3]:
arr1

array([1, 2, 3, 4, 5])

##### 2D numpy array

In [4]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [5]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

##### 3D numpy array

In [6]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [7]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### Using np.ones()

In [8]:
arr4=np.ones((5,2))

In [9]:
arr4

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
arr4=np.ones((2,5))

In [11]:
arr4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Using np.zeros()

In [12]:
arr5=np.zeros((1,1))

In [13]:
arr5

array([[0.]])

In [14]:
arr6=np.zeros((2,5))

In [15]:
arr6

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Using np.arange()


In [16]:
arr7=np.arange(10)

In [17]:
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr7=np.arange(12)

In [25]:
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Using np.reshape()

In [26]:
arr7.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
arr8=np.arange(24).reshape(3,4,2)

In [28]:
arr8

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

### Using np.linspace()

In [29]:
arr=np.linspace(-10,10,10)

In [30]:
arr

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [31]:
arr=np.linspace(2,3,4)

In [32]:
arr

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [33]:
arr=np.linspace(0,10,100).reshape(10,10)

In [34]:
arr

array([[ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
         0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091],
       [ 1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
         1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192],
       [ 2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
         2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293],
       [ 3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
         3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394],
       [ 4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
         4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495],
       [ 5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
         5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596],
       [ 6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
         6.56565657,  6.66666667,  6.76767677

### Using np.identity()

In [35]:
#Identity Matrix
arr=np.identity(3)

In [36]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
arr=np.identity(5)

In [38]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

###  Using copy()

In [39]:
arr=[1,2,3,4,5]

In [42]:
arr=arr.copy()

In [43]:
arr

[1, 2, 3, 4, 5]

# Numpy array Attributes and Properties

1. shape

2. ndim

3. size

4. itemsize

5. dtype

6. astype()

### Using shape attribute

In [54]:
arr=np.array([1,2,3,4])
arr.shape

(4,)

In [53]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1.shape

(2, 3)

In [52]:
arr2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr2.shape

(2, 2, 3)

In [50]:
arr3=np.array([[[1,2],[4,5]],[[7,8],[10,11]]])
arr.shape

(4,)

### Using ndim attribute

(to check how many dimensions)


In [55]:
arr=np.array([1,2,3,4])
arr.ndim

1

In [56]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1.ndim

2

In [57]:
arr2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr2.ndim

3

In [58]:
arr3=np.array([[[1,2,3],[4,5,6],[45,65,96]],[[7,8,9],[10,11,12],[69,36,45]]])
arr3.ndim

3

### Using size attribute

(to know how many elements present in numpy array)

In [61]:
arr=np.array([1,2,3,4])
arr.size

4

In [62]:
arr3=np.array([[[1,2,3],[4,5,6],[45,65,96]],[[7,8,9],[10,11,12],[69,36,45]]])
arr3.size

18

### Using itemsize attribute

(to know how much space is occupied by numpy array)

In [63]:
arr=np.array([1,2,3,4])
arr.itemsize

4

In [65]:
arr4=np.ones((2,3))
arr4.itemsize # because it generates float value

8

### Using dtype attribute

(to see which datatype we are using)

In [67]:
arr=np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [69]:
arr1=np.ones((2,3))
arr1.dtype

dtype('float64')

### Using  .astype()

(to covert datatypes)

In [70]:
arr4=np.ones((2,3))
arr4.astype('int')

array([[1, 1, 1],
       [1, 1, 1]])

In [72]:
arr=np.array([1,2,3,4])
arr.astype('float')

array([1., 2., 3., 4.])

# Numpy arrays advantages over Python lists

1. memory

2. speed

3. ease of use

# Numpy arrays basic operations

### Basic Operations

##### 1. A-b (item wise addition)

In [77]:
arr1=np.arange(1,11)
arr2=np.arange(11,21)
arr1+arr2

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

##### 2. A-b (item wise subtraction)

In [80]:
arr1=np.arange(1,11)
arr2=np.arange(11,21)
arr2-arr1

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

#### 3. A*b  (multiplying item wise)

In [78]:
arr1=np.arange(1,11)
arr2=np.arange(11,21)
arr1*arr2

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

##### 4. A/b (item wise division)

In [81]:
arr1=np.arange(1,11)
arr2=np.arange(11,21)
arr2/arr1

array([11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ,
        2.66666667,  2.42857143,  2.25      ,  2.11111111,  2.        ])

##### 5. A%b (item wise mod)

In [82]:
arr1=np.arange(1,11)
arr2=np.arange(11,21)
arr2%arr1

array([0, 0, 1, 2, 0, 4, 3, 2, 1, 0], dtype=int32)

##### 6. Power of (item wise)

In [83]:
arr1=np.arange(1,11)
arr2=np.arange(11,21)
arr2**arr1

array([         11,         144,        2197,       38416,      759375,
          16777216,   410338673, -1864941312,   565150579,   797966336],
      dtype=int32)

##### 7. b*2 (scalar multiplication)

In [79]:
arr1=np.arange(1,11)
arr1*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

##### 8. A+4 (scalar addition)

In [85]:
arr1=np.arange(1,11)
arr1+4

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

##### 9. b-4 (scalar substractions)

In [86]:
arr1=np.arange(1,11)
arr1-4

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

##### 10. b/2 (scalar division)

In [87]:
arr1=np.arange(1,11)
arr1/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

### Unary Operations

##### 1. np.min() (finding the minimum of numpy array)

In [88]:
arr1=np.arange(1,21)
np.min(arr1)

1

##### 2. np.max() (finding the minimum of numpy array)

In [89]:
arr1=np.arange(1,21)
np.max(arr1)

20

##### 3. np.sum() (sum of all elements of numpy array)

In [90]:
arr1=np.arange(1,21)
np.sum(arr1)

210

##### 4. axis=0/axis=1  

In [99]:
arr1=np.arange(12).reshape(3,4)
print(np.sum(arr1,axis=0)) #by column
print(np.sum(arr1,axis=1)) #by row


[12 15 18 21]
[ 6 22 38]


### Universal Functions

##### 1. np.exp()

In [104]:
arr1=np.arange(12).reshape(3,4) #exponential
np.exp(arr1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

##### 2. np.sqrt()

In [105]:
arr1=np.arange(12).reshape(3,4) #square root
np.sqrt(arr1)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

##### 3. np.log()

In [111]:
arr1=np.arange(1,13).reshape(3,4)
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

##### 4. np.sin()

In [106]:
arr1=np.arange(12).reshape(3,4)
np.sin(arr1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

##### 5. np.cos()

In [108]:
arr1=np.arange(12).reshape(3,4)
np.cos(arr1)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.83907153,  0.0044257 ]])

### Basic Statistics

##### 1. np.mean()

In [115]:
arr1=np.arange(12).reshape(3,4) #mean
np.mean(arr1)

5.5

##### 2. np.std()

In [116]:
arr1=np.arange(12).reshape(3,4) #standard deviasion
np.std(arr1)

3.452052529534663

##### 3. np.var() 

In [114]:
arr1=np.arange(12).reshape(3,4) #variance
np.var(arr1)

11.916666666666666

##### 4. np.median()

In [117]:
arr1=np.arange(12).reshape(3,4)
np.median(arr1)

5.5

### Boolean Numpy array

In [118]:
arr1=np.arange(12).reshape(3,4)
arr1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [120]:
arr1=np.arange(12).reshape(3,4)
arr1==11

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

# Numpy array Slicing & Indexing

### 2D numpy array

##### 1. Get first two rows

In [121]:
arr1=np.arange(12).reshape(3,4)
arr1[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

##### 2. Get first row and last row 

In [122]:
arr1=np.arange(12).reshape(3,4)
arr1[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

##### 3. Reverse the rows

In [123]:
arr1=np.arange(12).reshape(3,4)
arr1[::-1]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

##### 4.Get first column

In [124]:
arr1=np.arange(12).reshape(3,4)
arr1[:,0] #as of arr[rows,columns]

array([0, 4, 8])

##### 5. Get second and last column

In [125]:
arr1=np.arange(12).reshape(3,4)
arr1[:,1::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

##### 6. Get all four corners

In [126]:
arr1=np.arange(12).reshape(3,4)
arr1[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

##### 7. Get 1,2,5,6 from arr1

In [128]:
arr1=np.arange(12).reshape(3,4)
arr1[:2,1:3]

array([[1, 2],
       [5, 6]])

### 3D array

In [130]:
arr2=np.arange(24).reshape(3,2,4)
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

##### 1. Last column of all 3 matrices

In [129]:
arr2=np.arange(24).reshape(3,2,4)
arr2[:,:,-1] #as of arr[numbers,rows,columns]

array([[ 3,  7],
       [11, 15],
       [19, 23]])

##### 2. All corner items

In [132]:
arr2=np.arange(24).reshape(3,2,4)
arr2[:,:,::3]

array([[[ 0,  3],
        [ 4,  7]],

       [[ 8, 11],
        [12, 15]],

       [[16, 19],
        [20, 23]]])

##### 3. First item of every single matrix

In [133]:
arr2=np.arange(24).reshape(3,2,4)
arr2[:,:1,:1]

array([[[ 0]],

       [[ 8]],

       [[16]]])

# Traverse into a Numpy Array

In [136]:
for i in np.nditer(arr2):
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 

In [137]:
for i in np.nditer(arr1):
     print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 

# Reshaping Numpy Array

1. reshape()

2. transpose

3. ravel()

4. np.hstack()

5. np.vstack()

6. np.vsplit()

7. np.hsplit()

In [140]:
print(arr2)           #for referrence
print(arr2.shape)     #for referrence


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
(3, 2, 4)


### Using reshape()

In [141]:
arr2=np.arange(24).reshape(3,2,4)
arr2.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Using transpose

In [145]:
arr2=np.arange(24).reshape(6,4)
arr2.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

### Using ravel()

In [146]:
arr2=np.arange(24).reshape(3,2,4)

 #it will convert into 1D array
    
arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### Using np.hstack()

In [147]:
arr5=np.arange(6).reshape(2,3)
arr6=np.arange(6,12).reshape(2,3)

# Merging numpy arrays Horizontally

np.hstack((arr5,arr6))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### Using np.vstack()

In [148]:
arr5=np.arange(6).reshape(2,3)
arr6=np.arange(6,12).reshape(2,3)

# Merging numpy arrays Vertically

np.vstack((arr5,arr6))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### Using np.vsplit()

In [151]:
arr3

#for referrence

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [45, 65, 96]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [69, 36, 45]]])

In [152]:
np.vsplit(arr3,2) 

#it is the opposite of vertical stacking

[array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [45, 65, 96]]]),
 array([[[ 7,  8,  9],
         [10, 11, 12],
         [69, 36, 45]]])]

In [158]:
np.hsplit(arr3,3) 

#it is the opposite of horizontal stacking

[array([[[1, 2, 3]],
 
        [[7, 8, 9]]]),
 array([[[ 4,  5,  6]],
 
        [[10, 11, 12]]]),
 array([[[45, 65, 96]],
 
        [[69, 36, 45]]])]

# Fancy Indexing

##### If we want 1st,2nd last ,last row of arr3

In [172]:
arr3=arr2.reshape(6,4)
arr3[[0,-2,-1]]

array([[ 0,  1,  2,  3],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

##### If we want 1st,2nd last ,last column of arr3

In [173]:
arr3=arr2.reshape(6,4)
arr3[[0,-3,-2]][:,[0,-2,-1]]

array([[ 0,  2,  3],
       [12, 14, 15],
       [16, 18, 19]])